[package]
name = "dsa-in-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
cargo-modules = "0.21.1"

[dev-dependencies]
criterion = "0.5.0"

[[bench]]
name = "bubble_sort_bench"
harness = false
path = "benches/sorting/bubble_sort_bench.rs"